# _config.yml

# Analytics
google_analytics: G-D2RL4M3C84
analytics:
  provider                  : "google-gtag"
  google:
    tracking_id             : "G-D2RL4M3C84"
    measurement_id          : "G-D2RL4M3C84"
    anonymize_ip            : false
